### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [JoseExposito/touche#100]
### Is your feature request related to a problem? Please describe

Distros like Linux Mint and Elementary OS have started hiding or otherwise discouraging the use of unverified flatpaks. More will likely follow as verified apps approach 50% of Flathub

### Describe the solution you'd like

Could you verify the flatpak on Flathub so people on these distros can find it?

### Additional context

Here is a link to Flathub's verification documentation for app authors https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by JoseExposito** [comment]
Thanks for the heads up. I'll try to verify it once I find some free time :)

**Comment by JoseExposito** [comment]
Just fixed a couple of metadata issues that stopped the app to be verified. I'm publishing 2.0.13 which, hopefully, could be verified.

**Comment by Roman19S** [comment]
It's now verified! Thanks for the quick action
![Screenshot_20240823-085805_Firefox_1](https://github.com/user-attachments/assets/0b378c7d-1640-40e1-8cb6-207ccdbcda34)
