### ISSUE TITLE
App launches and window is empty.

### ISSUE THREAD

**Issue by mcoyle1960** [JoseExposito/touche#12]
I have a working install of touchegg.
Installed Touche flatpak.
When launched, I get a small window a few a few hundred pixels square. No options available. No text or controls at all in the box.
Resizing the box doesn't make a difference.

Thanks for your work!

**Comment by JoseExposito** [comment]
Hi and thanks for your bug report.

Could you include your logs please? Execute in a terminal:

```
$ flatpak run com.github.joseexposito.touche
```

Also, could you attach your Touchégg configuration, please? It is placed at `~/.config/touchegg/touchegg.conf`

**Comment by mcoyle1960** [comment]
Ugh! Thank you. The log showed I had an unclosed comment in touchegg.conf
config fixed. 
Touche fixed. Thanks.
