### ISSUE TITLE
Adding Gnome-Terminal as a new application in Touché selects the wrong WM_CLASS

### ISSUE THREAD

**Issue by martinmaehlmann** [JoseExposito/touche#14]
### Adding Gnome-Terminal as a new application in Touché selects the wrong WM_CLASS

If one adds a new application in Touché with the "plus" in the bottom left, and selects a gnome terminal, the application is added, but the gestures will not be registered. This is due to the fact that Touché selects the wrong `WM_CLASS`.

The required xprop output is as follows:

```xprop
WM_CLASS(STRING) = "gnome-terminal-server", "Gnome-terminal"
```

### Workaround
Replace the line `<application name="gnome-terminal-server">` in `~/.config/touchegg/touchegg.conf` with `<application name="gnome-terminal">`

### Expected behaviour

The correct `WM_CLASS` is selected.

### Actual behaviour

The wrong `WM_CLASS` is selected.

### Logs

No logs.

```touchegg.conf
<touchégg>
  <settings>
    <property name="animation_delay">150</property>
    <property name="action_execute_threshold">20</property>
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>
  <application name="gnome-terminal">
    <!-- Correct WM_CLASS>
  </application>
  <application name="gnome-terminal-server">
    <!-- Wrong WM_CLASS>
  </application>
</touchégg>
```

### Your environment

 * Touché version: 1.0.3
 * Touchégg version: v2.0.8
 * Operating System: !Pop_OS 20.10
 * Desktop Environment: Gnome
 * Installation method: Debian package...

**Comment by JoseExposito** [comment]
Thanks for your bug report. Yes, this is a bug :+1:
