### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by frederikheld** [JoseExposito/touche#16]
### Describe the bug

Touché does not save changed settings.

### Expected behaviour

I would either expect a save button to explicitly save settings but I can't find it anywhere. As I can't find it, I would expect Touché to save settings as they are changes.

### Actual behaviour

When being closed and re-opened, settings are back to default.

### Logs

If required, include logs of the bug:

```
$ flatpak run com.github.joseexposito.touche
(com.github.joseexposito.touche:2): Gjs-CRITICAL **: 23:14:30.073: JS ERROR: Gio.IOErrorEnum: Error creating directory /home/myaccount/.config/touchegg: Read-only file system
createDir@webpack:///../src/config/xml-config.js?:227:12
saveConfig@webpack:///../src/config/xml-config.js?:190:15
saveToFile@webpack:///../src/config/model.js?:101:54
saveSettings@webpack:///../src/main-view/content/gesture-list-row.js?:157:56
_init/<@webpack:///../src/main-view/content/gesture-list-row.js?:89:12
main@webpack:///../src/index.js?:71:22
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/app/bin/com.github.joseexposito.touche:11:17
```

This error occurs as soon as I change any setting. The FS is not read-only!

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it relevant.

--> doesn't exist

### Your environment

 * Touché version: no idea. I installed it today via "Software" (not "Ubuntu Software"!) and Touchegg via pa:touchegg/stable (as described in the docs)
 * Touchégg version: same
 * Operating System: Ubuntu 20.10
 * Desktop Environment: Gnome
 * Installation method: seems to be Flatpak

**Comment by frederikheld** [comment]
Fixed it by running `touchegg` in the terminal. For me the touchegg docs are not clear enough here. I thought this is only relevant if installed via downloaded .deb.

However, it is working now and it is awesome! Thanks for this great tool!

**Comment by JoseExposito** [comment]
Thanks for reporting this.

This is a bug, when running from Flatpak, if the folder `.config/touchegg` doesn't exists it doesn't have permissions to create it.

**Comment by JoseExposito** [comment]
Fixed, the patch will be released in 1.0.4

**Comment by siddhantladdha** [comment]
Same issue and conditions except for version changes which are mentioned below.
Touché: version 1.0.5. 
Touchegg version: 2.0.10.
Operating system: Pop! OS 20.04 LTS (based on Ubuntu 20.04 LTS)

However, one additional point I feel might be important is that my `.config/touchegg` is actually a soft link to `touchegg -> ../open_files/dotfiles/touchegg/.config/touchegg`.
@JoseExposito  should I open a new issue regarding this and attach the relevant logs there?

**Comment by JoseExposito** [comment]
@siddhantladdha yes, create a new issue and add the logs, please.
