### ISSUE TITLE
Touché doesn't start on Ubuntu 18.04

### ISSUE THREAD

**Issue by iamjackg** [JoseExposito/touche#18]
### Describe the bug

Touché doesn't start on Ubuntu 18.04

### Expected behaviour

The main window should appear

### Actual behaviour

Nothing happens :P

### Logs

When running manually from the terminal, this is all I get:

```
$ com.github.joseexposito.touche
Gjs-Message: 11:56:26.731: JS LOG: Granite is not available
Gjs-Message: 11:56:26.744: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 540 > eval 52]: reference to undefined property "forced"
Gjs-Message: 11:56:26.828: JS LOG: Reading configuration file "/home/jack/.config/touchegg/touchegg.conf"
Gjs-Message: 11:56:26.828: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 1251 > eval 54]: reference to undefined property "position"
Gjs-Message: 11:56:26.828: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 1322 > eval 109]: reference to undefined property "_text"

(com.github.joseexposito.touche:11390): Gjs-WARNING **: 11:56:26.830: JS ERROR: Error: Text data outside of root node.
Line: 0
Column: 28
Char: ]
error@webpack:///../node_modules/sax/lib/sax.js?:684:10
strictFail@webpack:///../node_modules/sax/lib/sax.js?:711:7
write@webpack:///../node_modules/sax/lib/sax.js?:1104:15
module.exports@webpack:///../node_modules/xml-js/lib/xml2js.js?:411:5
loadConfig@webpack:///../src/config/xml-config.js?:77:20
loadFromFile@webpack:///../src/config/model.js?:97:5
showMainView@webpack:///../src/app-window.js?:89:5
_init@webpack:///../src/app-window.js?:64:7
main/<@webpack:///../src/index.js?:66:22
main@webpack:///../src/index.js?:71:10
run@resource:///org/gnome/gjs/modules/package.js:225:12
@/usr/bin/com.github.joseexposito.touche:11:1

^C
```

Nothing appears, nothing else happens, and I have to Ctrl+C out of the app.

### Your environment

 * Touché version: 2.0.8
 * Touchégg version: 1.0.4
 * Operating System: Ubuntu 18.04
 * Desktop Environment: Gnome
 * Installation method: Debian package

**Comment by JoseExposito** [comment]
Hi! It looks like your config file (placed at `~/.config/touchegg/touchegg.conf`) contains text outside the root node.

If you are not familiar with XML, feel free to post it here so I can help you to fix it

**Comment by iamjackg** [comment]
I should have added that this happens even without a config file. I did notice that the error was coming from the XML parsing library, so I tried adding the default config from the touchegg repo, but that didn't work either.

**Comment by iamjackg** [comment]
Is there a fallback location for the config file somewhere that might be picked up instead? :thinking:

**Comment by iamjackg** [comment]
Ah, found it: https://github.com/JoseExposito/touche/blob/ccd7bcf29b573b8046686cc584d6452cab529b41/src/config/paths.js#L36

This file looks OK, and yet I still get the error. This is very odd!

**Comment by JoseExposito** [comment]
Yes, as you found out, the system level config file is placed at `/usr/share/touchegg/touchegg.conf`.

If `~/.config/touchegg/touchegg.conf` is not present, the system file is used.

Could you copy and paste the contents of your config file, pleas? (System and/or home please)
Just to make sure it is not corrupted. It is weird, because the parser is convinced that something is going on, but the default config should be fine.

**Comment by iamjackg** [comment]
Actually hang on -- I wonder if this is some weird UTF8 issue with `xml-js`, because it's reporting an error with a `[` character, but there definitely are no square brackets in the conf file. I get this same error even if I put random content in the file in both locations.

**Comment by iamjackg** [comment]
Ah-ha, here we go -- for whatever reason, `readFile` in `xml-config.js` is returning `"[object GjsModule byteArray]"` instead of the actual contents of the file. The XML library is then trying to parse _that_.

**Comment by iamjackg** [comment]
More clues! Here's a comment from somebody running into the same issue -- https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/520#issuecomment-489533051

Looks like it's an issue with my version of Gnome Shell being older, which makes sense since I'm on 18.04. I previously installed Touché on 20.04 and had no issues.

**Comment by iamjackg** [comment]
Alright, one last comment, then I'm done with all the spam. I managed to hack it together by simply returning `contents` in `readFile` and freeing it inside `loadConfig`. This is pretty ugly but at least it'll allow me to use it :)

If you get around to adding a conditional to fix this for older Gnome versions I'm happy to test it out for you!

Cheers, and thanks for building all this -- it's great and makes using Linux on my laptop a much, much nicer experience.

**Comment by JoseExposito** [comment]
Hi and thanks for investigating this.

I wish every bug report were like this one, where the reporter solve their own bug :laughing: 

Yes, it looks like the API is broken so, 2 options here:

- It shouldn't happen with the Flatpak version, so you can always use that build and get updates for free
- I know Flatpak is not for every one, so, does this method work for you?
```js
  /**
   * @param {string} path File path.
   * @returns {string} The file contents.
   */
  static readFile(path) {
    const file = Gio.File.new_for_path(path);
    const [success, contents] = file.load_contents(null);

    if (!success) {
      // TODO Handle this error
      throw new Error('Error loading config file');
    }

    let str = ByteArray.toString(contents, 'UTF-8');

    // Workaround for GNOME 3.28:
    // https://github.com/JoseExposito/touche/issues/18
    // https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/520#issuecomment-489533051
    if (str.match(/GjsModule byteArray/)) {
      str = `${contents}`;
    }

    GLib.free(contents);
    return str;
  }
```

**Comment by JoseExposito** [comment]
I just tested it and it worked, fixed in master in case you want to build it :smile:

**Comment by iamjackg** [comment]
Thank you so much! Sorry for the delay, I had a busy week :grimacing:
