### ISSUE TITLE
Touchpad disabled on Gnome ignored

### ISSUE THREAD

**Issue by juxuanu** [JoseExposito/touche#19]
### Describe the bug

If the touchpad is disabled, basically with the dedicated key that some laptops have, Gnome detects this, but Touche doesn't. It still works.

### Expected behaviour

Disabling the touchpad should disable the gestures until is back on.

```
$ com.github.joseexposito.touche
```
### Your environment

 * Touché version: 1.0.4
 * Touchégg version: 2.0.9
 * Operating System: Arch Linux
 * Desktop Environment: Gnome
 * Installation method: AUR packages

**Comment by JoseExposito** [comment]
Hi

Thanks for the bug report. Could you clarify the bug a little bit, please?

Touché is the graphical user interface used to configure features. Do you mean that the user interface should be disabled? Or that gestures should stop?

**Comment by juxuanu** [comment]
I am sorry I did not follow up on the bug report, @JoseExposito .

1) Please, could you move this to touchegg repo?
2) Clarification: when disabling the touchpad:

![image](https://user-images.githubusercontent.com/24759034/118481992-70862300-b714-11eb-815f-e030a16f39ed.png)

the gestures continue to work. They should be disabled, as the user expectes the touchpad to be disabled.

**Comment by JoseExposito** [comment]
Closing in favor of https://github.com/JoseExposito/touchegg/issues/492
