### ISSUE TITLE
How go back in browser? (Alt+Left key)

### ISSUE THREAD

**Issue by alessiobb1** [JoseExposito/touche#21]
### Describe the bug

Hi! If i try to import Left Alt + Left arrow key it don't work... why? This is a picture (i'm italian and this is in italian) of how I configured it... Tranks!

![immagine](https://user-images.githubusercontent.com/65780895/119255680-64d7a800-bbbd-11eb-8bc7-23608fa7ef47.png)

### Expected behaviour

Work (go back in firefox)

### Actual behaviour

Nothing

### Logs

If required, include logs of the bug:
Gjs-Message: 11:54:13.110: JS LOG: Granite is not available
Gtk-Message: 11:54:13.161: Failed to load module "xapp-gtk3-module"

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

#<application name="firefox">
#    <gesture type="PINCH" fingers="2" direction="IN">
#    <action type="SEND_KEYS">
#     <repeat>true</repeat>
#      <modifiers>Control_L</modifiers>
#     <keys>KP_Subtract</keys>
#      <decreaseKeys>KP_Add</decreaseKeys>
#    </action>
#   </gesture>
#    <gesture type="PINCH" fingers="2" direction="OUT">
#      <action type="SEND_KEYS">
#        <repeat>true</repeat>
#        <modifiers>Control_L</modifiers>
#        <keys>KP_Add</keys>
#      <decreaseKeys>KP_Subtract</decreaseKeys>
#     </action>
#   </gesture>
#    <gesture type="SWIPE" fingers="3" direction="RIGHT">
#      <action type="SEND_KEYS">
#        <modifiers>RAlt+Right</modifiers>
#        <keys>Alt+Right</keys>
#       <repeat>false</repeat>
#        <on>begin</on>
#      </action>
#   </gesture>
#    <gesture type="SWIPE" fingers="3" direction="LEFT">
#     <action type="SEND_KEYS">
#        <modifiers>Alt_L+KP_Left</modifiers>
#        <keys>Alt_L+KP_Left</keys>
#        <repeat>false</repeat>
#        <on>begin</on>
#      </action>
#    </gesture>
#  </application>

### Your environment

 * Touché version: Last
 * Touchégg version: Last
 * Operating System: Linux Mint (Ubuntu based)
 * Desktop Environment: Cinnamon (Gnome based)
 * Installation method: Flatpak

**Comment by JoseExposito** [comment]
Hi!

This is the config you need:

![Screenshot from 2021-05-23 18 46 31](https://user-images.githubusercontent.com/1335948/119269297-3b3b7280-bbf7-11eb-9f85-1516731a05b3.png)

Check this out for more information: https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys
