### ISSUE TITLE
UI Is too big for HiDPI

### ISSUE THREAD

**Issue by FlyinPancake** [JoseExposito/touche#22]
I'm running Touche on pop_os 20.10 but the UI on 200% scaling which is optimal for my eyes is simply too big to fit on the screen. My laptop's resolution is 2560x1440 = 2k 16:9. Could you make the minimum UI height a bit shorter to it can fit in the screen ?

**Comment by JoseExposito** [comment]
Hi and thanks for the bug report.

Could you attach an screenshot, please? Just to try to figure out the optimal height.

**Comment by FlyinPancake** [comment]
![image](https://user-images.githubusercontent.com/36113055/119534970-cd728080-bd87-11eb-95f1-234d003e3fa7.png)
Now looking at it it seems like it just fits, but I feel like making it shorter by 50-100 pixels should make it more visually appealing.

**Comment by JoseExposito** [comment]
Fixed, the fix will be released in v1.0.6
