### ISSUE TITLE
Pb with meson

### ISSUE THREAD

**Issue by Desiderius77** [JoseExposito/touche#23]
I have recently upgraded my distro and Touché is no more starting !

Looking at the details, I have found the reason :

"ninja: Entering directory `build'
[1/2] Installing files.

ERROR: Build directory has been generated with Meson version 0.57.2, which is incompatible with the current version 0.58.0.
FAILED: meson-install"

Is it possible to have a version upgraded to Meson  0.58 ?

**Comment by JoseExposito** [comment]
Remember to delete the `build` directory after upgrading meson:

```
$ rm -fr build
$ meson .....
```

That should fix your problem... Or you can always install Touché from Flathub:
https://flathub.org/apps/details/com.github.joseexposito.touche
