### ISSUE TITLE
Touche window minimum size is still too big for small monitors

### ISSUE THREAD

**Issue by narFnarF** [JoseExposito/touche#28]
### Describe the bug
The window is slightly too tall for small monitors.

My monitor is 1280x800 and I'm missing the bottom part of the window: it gets hidden behind my taskbar.
Screenshot: https://i.imgur.com/KyAKphH.png

### Expected behaviour

Allow the Touch window to be smaller.
Minimum height should be 400 (currently about 800)
Minimum width should be 700 (currently it's about 1000)

### Actual behaviour

The window is cropped on small monitors.

### Your environment

 * Touché version: 1.0.5
 * Touchégg version: touchegg/groovy,now 202106090721-stable-2.0.10~ubuntu20.10.1 amd64
 * Operating System: Lubuntu
 * Desktop Environment: i don't know
 * Installation method: Flatpak

**Comment by JoseExposito** [comment]
Hi! I just released 1.0.6 with a smaller window size. You'll receive an update today or tomorrow and the window will hopefully fit in your screen :)
