### ISSUE TITLE
Question: How to launch Touche?

### ISSUE THREAD

**Issue by narFnarF** [JoseExposito/touche#29]
Sorry, this is a very noob question. I'm new with flatpacks and linux in general...

After installing through flathub, what's the normal way to launch Touche? So far, the only way I found was to open my software manager, locate Touche in the list of installed app and use the Launch button. (Screenshot: https://i.imgur.com/FEOJTb2.png )

Touche doesn't show up in my Application Menu. Is that normal?

**Comment by JoseExposito** [comment]
No, it's not normal, it should be shown in your application menu.
Is still not there after a reboot? (Even though a reboot should not be necessary)

From you previous issue report, I see you are using LXDE. Make sure to check the "Accessories" section of your app menu.

**Comment by narFnarF** [comment]
I can see it now in the Accessories section after a reboot. Maybe I missed it the first time?
Sorry, and thanks for your help! :D
