### ISSUE TITLE
RPM Release Package for Fedora

### ISSUE THREAD

**Issue by CleanHit** [JoseExposito/touche#3]
Is it possible to add RPM packages for Fedora in releases?

**Comment by JoseExposito** [comment]
Of course, it is in my to do list.

I'm just curious, why you prefer RPM over Flatpak? Flatpak is already shipped with Fedora and you get updates.

**Comment by CleanHit** [comment]
I didn't try to really use Flatpak so far, but l'll give it a go now. I can close this ticket if you want or you can mark it as __enhancement__ for others that really want to have an RPM package.

**Comment by JoseExposito** [comment]
Don't worry, RPM support is something I'll like to add. Labeled as enhancement :smile:

**Comment by starvsion** [comment]
I think the flatpak version is suffering from some graphic issue like zoom flatpak version. Zoom one you cannot share screen in wayland, Touche in this case i cannot add new application, because i cannot select window that's not Touche.

**Comment by JoseExposito** [comment]
It's finally available :tada: 
https://github.com/JoseExposito/touche/releases/tag/1.0.6

**Comment by CleanHit** [comment]
> It's finally available 🎉
> https://github.com/JoseExposito/touche/releases/tag/1.0.6

Thanks 🎉 but I got used to Flatpak and I like it 😅
