### ISSUE TITLE
Installing Touche from same repository of Touchegg

### ISSUE THREAD

**Issue by anir92** [JoseExposito/touche#32]
Hi,
I am using Ubuntu 20.04 LTS. The "npm" requires now-unsupported python2 to be installed to the system. I use some other softwares for my daily work, which rely on the Python3. I am not an expert, but I fear installing pyhton2 will mess up the python paths for other softwares that I daily use. On the other hand installing Flatpak will probably mess up Ubuntu Software store, which is by default a snap-store (If I am not wrong), and create a conflicting copy of flatpak-store. (I may sound technically wrong, apologies for that).

So, my question, is there any simple method to install Touche on my Ubuntu 20.04 LTS, just the way I installed Touchegg on it ? And I want to request the developer to add Touche to the same repository as that of Touchegg, so that installation can be smooth.

**Comment by JoseExposito** [comment]
Hi @anir92 

If I'm not mistaken, `npm` doesnt require Python:
https://packages.ubuntu.com/focal/npm

Also, it is a build dependency, you can uninstall it once you are done with the installation... Or install one of the `deb` packages:
https://github.com/JoseExposito/touche/releases/tag/1.0.6

However, FlatHub is the recommended way of installing applications, you shouldn't have any problems using them:
https://flatpak.org/setup/Ubuntu/

Just skip step 2 and install Touché from the command line:

```bash
$ flatpak install flathub com.github.joseexposito.touche
```

**Comment by JoseExposito** [comment]
Closing this one in favour of https://github.com/JoseExposito/touche/issues/17
