### ISSUE TITLE
The GNOME 3.38 runtime is no longer supported

### ISSUE THREAD

**Issue by vibhavkharangate** [JoseExposito/touche#37]
### Describe the bug

updating the flatpak gives the following warning:

Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.joseexposito.touche

**Comment by JoseExposito** [comment]
Thanks for the heads up, fixed!
