### ISSUE TITLE
Error building for Arch/Manjaro

### ISSUE THREAD

**Issue by yochananmarqos** [JoseExposito/touche#4]
Building from source:

```
(com.github.joseexposito.touche:578367): Gjs-CRITICAL **: 10:37:15.959: JS ERROR: Error: Module build failed (from ../touche-1.0.2/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-class-properties'
Require stack:
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/files/plugins.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/files/index.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/index.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/babel-loader/lib/index.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/loader-runner/lib/loadLoader.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/loader-runner/lib/LoaderRunner.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/webpack/lib/NormalModule.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/webpack/lib/NormalModuleFactory.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/webpack/lib/Compiler.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/webpack/lib/webpack.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/webpack/lib/index.js
- /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/bundle/scripts/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at resolve (node:internal/modules/cjs/helpers:98:19)
    at resolveStandardizedName (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePlugin (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/files/plugins.js:44:10)
    at loadPlugin (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at createDescriptor (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/mnt/storage/pkgbuilds/touche/src/touche-1.0.2/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@webpack:///../touche-1.0.2/src/index.js?:1:7
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:13:1
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:14:12
@/usr/bin/com.github.joseexposito.touche:11:1


(com.github.joseexposito.touche:578367): Gjs-CRITICAL **: 10:37:15.959: Script /usr/bin/com.github.joseexposito.touche threw an exception
```
It should not be referencing the build directory, for one. 

Installing from DEB:
```
Gjs-Message: 10:50:39.035: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 305 > eval 25]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one

(com.github.joseexposito.touche:585716): Gjs-CRITICAL **: 10:50:39.079: JS ERROR: Error: Requiring Wnck, version none: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
@webpack:///../src/add-app-view/index.js?:43:14
../src/add-app-view/index.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:19:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1345:41
@webpack:///../src/app-window.js?:7:90
../src/app-window.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:30:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1345:41
@webpack:///../src/index.js?:2:88
../src/index.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:129:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1345:41
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1407:30
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1409:12
@/usr/bin/touche:11:1


(com.github.joseexposito.touche:585716): Gjs-CRITICAL **: 10:50:39.079: Script /usr/bin/touche threw an exception
```

I have GTK 2, 3 & 4 installed, appparently that's throwing it off. `libwnck3` is installed, but it seems it can't find the version. I'm using Manjaro GNOME.

**Comment by JoseExposito** [comment]
Hi! Thanks for your report.

> Building from source

It looks like you are missing the `npm install` step. 
Could you copy and paste the commands you are using to build it and there output, please?

By the way, there is a build on Flathub. I tested it on Manjaro and it worked without problems.

**Comment by yochananmarqos** [comment]
> It looks like you are missing the npm install step.

I had tried that, but the result was the same. You didn't mention that in your [installation](https://github.com/JoseExposito/touche/blob/master/HACKING.md#installation) steps, either.

> Could you copy and paste the commands you are using to build it and ~~there~~ their output, please?

The output is above.

<details>
<summary>PKGBUILD (from source)</summary>

```
pkgname=touche
pkgver=1.0.2
pkgrel=1
pkgdesc="The desktop application to configure Touchégg "
arch=('x86_64')
url="https://github.com/JoseExposito/touche"
license=('GPL3')
depends=('gjs' 'gtk3' 'libwnck3' 'touchegg')
makedepends=('meson' 'npm' 'appstream-glib')
checkdepends=('appstream' 'desktop-file-utils')
source=("$pkgname-$pkgver.tar.gz::$url/archive/$pkgver.tar.gz")
sha256sums=('b1e82204bfb5e2181c8213e4fc2cd16ebd3e2da5a3fc3eaf647808ca515183ae')

build() {
	export npm_config_cache="$srcdir/npm_cache"

	npm install "$pkgname-$pkgver" --cache "$srcdir/npm-cache"

	arch-meson -Dtarget-de=gnome "$pkgname-$pkgver" build
	meson compile -C build
}

check() {
	meson test -C build --print-errorlogs
}

package() {
	DESTDIR="$pkgdir" meson install -C build

	ln -s "/usr/bin/com.github.joseexposito.$pkgname" "$pkgdir/usr/bin/$pkgname"
}
```

</details>


<details>
<summary>PKGBUILD (from DEB)</summary>

```
pkgname=touche-bin
pkgver=1.0.2
pkgrel=1
pkgdesc="The desktop application to configure Touchégg "
arch=('x86_64')
url="https://github.com/JoseExposito/touche"
license=('GPL3')
depends=('gjs' 'gtk3' 'libwnck3' 'touchegg')
provides=("${pkgname%-bin}")
conflicts=("${pkgname%-bin}")
source=("https://github.com/JoseExposito/touche/releases/download/$pkgver/${pkgname%-bin}_${pkgver}_amd64.deb")
sha256sums=('bafeca1d95a5bf7ef7f87cf865c233fbaff0d097127a52d40ecdf2fbf9efbf5c')

package() {
	bsdtar -xvf data.tar.xz -C "$pkgdir"

	ln -s "/usr/bin/com.github.joseexposito.${pkgname%-bin}" "$pkgdir/usr/bin/${pkgname%-bin}"
}
```

</details>

> there is a build on Flathub

I don't use Flatpaks or Snaps.

**Comment by JoseExposito** [comment]
Hi!

I just compiled and installed it from master on Manajaro (KDE) using this commands:

```bash
$ sudo pamac install gjs gtk3 glib2 libwnck3 meson nodejs npm appstream desktop-file-utils
$ meson build --prefix=/usr -Dtarget-de=gnome
$ ninja -C build
$ sudo ninja -C build install
```

It runs using `com.github.joseexposito.touche` without problems. Could it be an issue in the PKGBUILD?

> I had tried that, but the result was the same. You didn't mention that in your installation steps, either.

npm dependencies are installed by meson unless you set a flag, that's why it is not a required step in the build instructions.

Let me know if you have issues compiling it with meson and if you need more information about my system (package versions, etc)

**Comment by yochananmarqos** [comment]
> sudo pamac

Don't use `sudo` with `pamac`, it will prompt when elevation is required.

> I just compiled and installed it from master on Manajaro (KDE) using this commands

That's great, but now you have untracked files installed in the system that could cause file conflicts in the future. That's why with Arch-based distros, `pacman` should always be used to install things. 

One difference is I'm using the [`arch-meson`](https://git.archlinux.org/svntogit/packages.git/tree/trunk/arch-meson?h=packages/meson) wrapper, but I don't see how any of the additional flags would break anything.

> Let me know if you have issues compiling it with meson and if you need more information about my system (package versions, etc)

That should not matter as long as you're fully up to date. Foreign packages (like from the AUR) should be built in a clean chroot. Otherwise environment / user variables can cause things to go wrong and also ensures a reproducible build. I think this is why it's working for you since your package is finding the `npm` dependencies somewhere, but I do not have any `npm` packages installed.

If you want to reproduce the issue, you'll need to install it with my PKGBUILD:

First create a `touche` folder somewhere and paste my PKGBUILD into a text file called `PKGBUILD`. We'll say it's located in `~/temp/touche`.

```
sudo pacman -Syu --needed base-devel manjaro-chrootbuild yay
yay -S touchegg # If you don't already have it installed
cd temp
sudo chrootbuild -p touche -c
sudo pacman -U /var/lib/chrootbuild/build/touche-1.0.2-1-x86_64.pkg.tar.zst
```

**Comment by JoseExposito** [comment]
> Don't use sudo with pamac, it will prompt when elevation is required.

Cool, I'm not an Arch/Manjaro user, but it's good to know.

Returning to the main topic, it looks like the problem with the PKGBUILD is that the `node_modules` folder is not in the right directory.

A couple notes:

> npm install "$pkgname-$pkgver"

This line is throwing a warning:

```
npm WARN saveError ENOENT: no such file or directory, open '/var/lib/chrootbuild/build/touche/src/build/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/lib/chrootbuild/build/touche/src/build/package.json'
npm WARN build No description
npm WARN build No repository field.
npm WARN build No README data
npm WARN build No license field.
```

This step is not required, however, if you want to keep it, the `prefix` option seems to work:

```
npm install --prefix "$pkgname-$pkgver"
```

Personally, I'd keep it because it makes the PKGBUILD more resilient to future changes.


> arch-meson -Dtarget-de=gnome "$pkgname-$pkgver" build

The main problem is with this `build` directory. The build expects to find the `node_modules` folder on the same level as` meson.build`. So, I can think of 2 options:

The first one is changing the `build` folder:
```
arch-meson -Dtarget-de=gnome "$pkgname-$pkgver" "$pkgname-$pkgver/build"
```

However, I don't know if building in `$srcdir/build` is some sort of best practice. If that's the case, the second option could be moving the `package.json` file to `$srcdir/build` and install there with `npm install --prefix "$srcdir/build"`.

Here is a working PKGBUILD using the first option:

```
pkgname=touche
pkgver=1.0.2
pkgrel=1
pkgdesc="The desktop application to configure Touchégg "
arch=('x86_64')
url="https://github.com/JoseExposito/touche"
license=('GPL3')
depends=('gjs' 'gtk3' 'libwnck3' 'touchegg')
makedepends=('meson' 'npm' 'appstream-glib')
checkdepends=('appstream' 'desktop-file-utils')
source=("$pkgname-$pkgver.tar.gz::$url/archive/$pkgver.tar.gz")
sha256sums=('b1e82204bfb5e2181c8213e4fc2cd16ebd3e2da5a3fc3eaf647808ca515183ae')

build() {
	export npm_config_cache="$srcdir/npm_cache"

	npm install --prefix "$pkgname-$pkgver"

	arch-meson -Dtarget-de=gnome "$pkgname-$pkgver" "$pkgname-$pkgver/build"
	meson compile -C "$pkgname-$pkgver/build"
}

check() {
	meson test -C "$pkgname-$pkgver/build" --print-errorlogs
}

package() {
	DESTDIR="$pkgdir" meson install -C "$pkgname-$pkgver/build"

	ln -s "/usr/bin/com.github.joseexposito.$pkgname" "$pkgdir/usr/bin/$pkgname"
}
```

-------------

By the way, not related, but I'm intermentelly getting this error:

```
1/3 Validate desktop file   OK             0.00s
2/3 Validate appstream file TIMEOUT        30.01s
3/3 Validate schema file    OK             0.01s

The output from the failed tests:

2/3 Validate appstream file TIMEOUT        30.01s

--- command ---
08:55:55 /usr/bin/appstream-util validate-relax data/com.github.joseexposito.touche.appdata.xml
--- stdout ---
data/com.github.joseexposito.touche.appdata.xml: 
-------


Summary of Failures:

2/3 Validate appstream file TIMEOUT        30.01s
2/3 Validate appstream file TIMEOUT        30.01s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
```

**Comment by yochananmarqos** [comment]
> The build expects to find the node_modules folder on the same level as meson.build

Aha! That was what I was missing. Finally it works, hooray! I just added it to the AUR and added you as a Co-Maintainer: [`touche`](https://aur.archlinux.org/packages/touche/)

> the prefix option seems to work

It's easier to cd into `"$pkgname-$pkgver"` instead:

<details>
<summary>PKGBUILD</summary>

```
pkgname=touche
pkgver=1.0.2
pkgrel=1
pkgdesc="The desktop application to configure Touchégg "
arch=('x86_64')
url="https://github.com/JoseExposito/touche"
license=('GPL3')
depends=('gjs' 'gtk3' 'libwnck3' 'touchegg')
makedepends=('meson' 'npm' 'appstream-glib')
checkdepends=('appstream' 'desktop-file-utils')
source=("$pkgname-$pkgver.tar.gz::$url/archive/$pkgver.tar.gz")
sha256sums=('b1e82204bfb5e2181c8213e4fc2cd16ebd3e2da5a3fc3eaf647808ca515183ae')

build() {
	export npm_config_cache="$srcdir/npm_cache"

	cd "$pkgname-$pkgver"
	npm install

	arch-meson -Dtarget-de=gnome . build
	meson compile -C build
}

check() {
	cd "$pkgname-$pkgver"
	meson test -C build --print-errorlogs
}

package() {
	cd "$pkgname-$pkgver"
	DESTDIR="$pkgdir" meson install -C build

	ln -s "/usr/bin/com.github.joseexposito.$pkgname" "$pkgdir/usr/bin/$pkgname"
}
```

</details>

> I'm intermentelly getting this error

I can't reproduce it, but I've seen it happen randomly before.

The target Gtk version needs to be specified. I have Gtk 2 & 3 installed right now. I had Gtk 4 installed before, but it caused issues with another program that wasn't targeting a Gtk version, either.
```
Gjs-Message: 13:07:46.951: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 305 > eval 25]: Requiring Gtk but it has 2 versions available; use imports.gi.versions to pick one
```

I'm guessing `granite` is only needed for `target-de=elementary`?
```
Gjs-Message: 13:07:46.972: JS LOG: Granite is not available
```

**Comment by JoseExposito** [comment]
Cool, thanks for adding it to AUR :smile: 

>  I just added it to the AUR and added you as a Co-Maintainer: touche

I think you added @jbouter as co-maintaner. And it is absolutely fine, he's been doing a fantastic job maintaining Touchégg.
My username on AUR is `JoseExposito`, in case you need to ping me.

> The target Gtk version needs to be specified. I have Gtk 2 & 3 installed right now. I had Gtk 4 installed before, but it caused issues with another program that wasn't targeting a Gtk version, either.

[In theory](https://github.com/JoseExposito/touche/blob/master/src/index.js#L26), I'm selecting GTK 3, but that warning should not be shown. I opened a different issue (https://github.com/JoseExposito/touche/issues/8)

> I'm guessing granite is only needed for target-de=elementary?

Yes, it is not a warning, it is a log I'm printing to make my life easier when I have the logs from a bug report.

**Comment by yochananmarqos** [comment]
> I think you added @jbouter as co-maintainer

Oops. A case of mistaken identity. I removed him for now.

**Comment by jbouter** [comment]
> Oops. A case of mistaken identity. I removed him for now.

Aw.

**Comment by yochananmarqos** [comment]
@jbouter I can add you again if you'd like to help maintain it.

**Comment by jbouter** [comment]
@yochananmarqos Nah, it's alright :-) I don't use Arch myself (anymore) except in a VM. I'm actually looking into using GitHub actions for automatic AUR commits as long as the tests succeed for the packages I do maintain.

**Comment by yochananmarqos** [comment]
> I'm actually looking into using GitHub actions for automatic AUR commits 

Let me know how that goes, shoot me an email or message me on Telegram.
