### ISSUE TITLE
Please add an option for tap functions for touchpad too.

### ISSUE THREAD

**Issue by abinlatheef** [JoseExposito/touche#43]
Touche says "Tap gestures are available only on touch screens". Please add an option for touch-pads too. I had been trying to find a way to use three finger tap as shortcut and failed. And why it is left out in the first place?

**Comment by JoseExposito** [comment]
I'm afraid it is not possible. libinput maps 1 finger tap to left click, 2 fingers to right click and 3 finger to middle click (you can use it to copy and paste text or close browser tabs, for example).

There is no way to change that behaviour from Touchégg.
