### ISSUE TITLE
[Question] Global gestures with 4 fingers, browser with 3 fingers possible?

### ISSUE THREAD

**Issue by zilexa** [JoseExposito/touche#44]
Just wondering, I am using Manjaro Gnome and just found out this little tool via the application launcher: Touche. 
I just wonder if I can set Global Gestures to 4 fingers instead of 3?
Makes it a bit easier to use them together with the browser. I am used to 4 finger global gestures (coming from Macbook) and 3 finger gestures for the browser (Firefox).

**Comment by JoseExposito** [comment]
I guess you are also using [X11Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures)? If so, type "Extensions" in the app launcher and search for the extension.

In the extension settings you can switch between 3 and 4 finger gestures. Logout and login to apply the changes.

There is a bug I couldn't fix yet (https://github.com/JoseExposito/touche/issues/40) that'll force you to open `~/.config/touchegg/touchegg.conf` and manually remove the wrong gestures, but hopefully it'll be easy enough to fix.

**Comment by JoseExposito** [comment]
Can you confirm in Settings -> About -> Windowing System that you are using X11, please?

It's weird that doesn't work at all, but it could be a bug.

If using X11, please attach your configuration placed at `~/.config/touchegg/touchegg.conf`, let's see if there is something weird there.

**Comment by zilexa** [comment]
As said I use Manjaro Gnome, a clean, new install. 
I now understand that means I use Wayland and I understand Touchegg doesn't support Wayland.
