### ISSUE TITLE
can't add new applications to Touche

### ISSUE THREAD

**Issue by nabeelmoeen** [JoseExposito/touche#45]
### Describe the bug

When trying to add new application to the Touche UI the cursor changes to a 'cross-hair' but when moving the mouse to any window the cursor changes back to the regular pointer and clicking on application windows has no effect.

### Expected behaviour
Not sure, haven't used the app before, but would expect when the 'add app' icon is clicked and then mouse clicked over another app window it should get added to touche.

### Your environment

 * Touché version:
 * Touchégg version: 2.0.11
 * Operating System: Fedora 34
 * Desktop Environment: KDE Wayland
 * Installation method: pre-installed, assuming it's flatpak

**Comment by JoseExposito** [comment]
> Desktop Environment: KDE Wayland

Touchégg is X11 only:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

Unfortunately, Touchégg won't work on Wayland for technical reasons. The good news are that on Wayland gestures are available to apps and desktop environments, so it's a matter of time that you get support out of the box.
