### ISSUE TITLE
Unsatisfied dependency: gtk

### ISSUE THREAD

**Issue by ryanknutson** [JoseExposito/touche#46]
### Describe the bug

When I try to start the program it says "Unsatisfied dependency: gtk" even though I have GTK3 and GTK2 packages installed:
`x11-libs/gtk+-3.24.29
x11-libs/gtk+-2.24.33`

### Expected behaviour

The program should start

### Actual behaviour

It doesn't start

### Logs

If required, include logs of the bug:

```
$ flatpak run com.github.joseexposito.touche
# or
$ com.github.joseexposito.touche
```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Touché version: commit 91a8e2a901440c5ad2c4fb5aed7b43fce0003682
 * Touchégg version: v2.0.11
 * Operating System: Ubuntu, Fedora, Arch Linux... Gentoo
 * Desktop Environment: Gnome, KDE, Xfce...         Xfce4
 * Installation method: Flatpak, Debian package...    installed from source

**Comment by JoseExposito** [comment]
Hi!

I'm in the middle of a migration to GTK 4. Please use a stable release when possible:
https://github.com/JoseExposito/touche/releases/tag/1.0.7

I don't test intermediate builds as much as I test stable tags and I can't guarantee that the latest commit works as expected (or works).

You can git checkout a tag or download the source code from the release page.
