### ISSUE TITLE
touche unconditionally overwrites existing `touchegg.conf` without warning.

### ISSUE THREAD

**Issue by dreirund** [JoseExposito/touche#48]
### Describe the bug

When I change anything in `touche`, an existing `touchegg.conf` is overwritten without warning. Entries not understood by `touche` are lost.

### Expected behaviour

Ask before overwriting an existing configuration file; keep non-understood entries or ask what to do with them; offer a side-by-side-view mode of original file and file that `touche` would write.

### Actual behaviour

When I change anything in `touche`, an existing `touchegg.conf` is overwritten without warning. Entries not understood by `touche` are lost.

### Logs

 * Touché version: *2.0.0*
 * Touchégg version: *2.0.11*
 * Operating System: Ubuntu, Fedora, Arch Linux...: *Artix GNU/Linux*
 * Desktop Environment: Gnome, KDE, Xfce...: *No full Desktop environment. Just plain window manager (`xfwm4`) and taskbar (`xfce4-taskbar`), software to autostart started via `~/.xinitrc`.*
 * Installation method: Flatpak, Debian package...: *[Arch Linux AUR package `touchegg-nosystemd`](https://aur.archlinux.org/packages/touchegg-nosystemd/).*

**Comment by JoseExposito** [comment]
Hi and thanks for your bug report,

By design, Touché keeps only valid configuration in the config file. What's the use case for this feature? What kind of non working configuration do you want to keep in your configuration file?

**Comment by felixbecker2** [comment]
> The issue is that "&" is not valid XML,

thanks.

Then I make the [feature request]() that Touché does print to `stderr` what it cannot correctly parse and quits with a non-zero exitcode (instead of beeing stuck with not-specific messages).
