### ISSUE TITLE
OpenGL error when opening the app

### ISSUE THREAD

**Issue by fsevenm** [JoseExposito/touche#49]
### Describe the bug

Just installed the app normally using flatpak. Then when tried to open in Terminal got OpenGL error.

### Expected behaviour

The app should open.

### Actual behaviour

The don't open.

### Logs

```
$ flatpak run com.github.joseexposito.touche
...
...
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0

$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

I use default configuration. Didn't change anything in the config.

### Your environment

 * Touché version: 2.0.0
 * Touchégg version: 2.0.11
 * Operating System: Ubuntu
 * Desktop Environment: Gnome
 * Installation method: Flatpak

**Comment by fsevenm** [comment]
What about this _...I don't know what is going on and also the dark theme does not work for me._, totally different issue right?

**Comment by JoseExposito** [comment]
Just pushed a release with the fix, you should receive an update in a few hours.

@fsevenm it looks like a different issue, probably related to the recent migration of Touché to GTK 4 and libadwaita. As far as I know Ubuntu is not fully migrated yet, but I'll need to do some testing. What Ubuntu version are you using?

**Comment by fsevenm** [comment]
> Just pushed a release with the fix, you should receive an update in a few hours.
> 
> @fsevenm it looks like a different issue, probably related to the recent migration of Touché to GTK 4 and libadwaita. As far as I know Ubuntu is not fully migrated yet, but I'll need to do some testing. What Ubuntu version are you using?

I am using Ubuntu 21.04, Gnome 3.38.x

**Comment by JoseExposito** [comment]
Just installed Ubuntu in a VM and it looks like other GTK 4 + libadwaita apps, like [TextEditor](https://flathub.org/apps/details/org.gnome.TextEditor), do not follow the dark theme preferences.

This feature will ship with [GNOME 42](https://www.omgubuntu.co.uk/2021/10/gnome-42-dark-style-preference), so we will have to wait a bit...
