### ISSUE TITLE
Add ARM builds to releases

### ISSUE THREAD

**Issue by m-roberts** [JoseExposito/touche#5]
Hi - would love for this application to have the same ARM builds as the [2.0.7 release of Touchegg](https://github.com/JoseExposito/touchegg/releases/tag/2.0.7)!

**Comment by JoseExposito** [comment]
Yes! I had some issues generating the builds that I need to investigate. Meanwhile you can use the Flatpak version, an `aarch64` build is automatically generated.

**Comment by JoseExposito** [comment]
@m-roberts do you know if there is any difference in [pi-top/action-debian-package](https://github.com/pi-top/action-debian-package) in terms of internet access when building for ARM?

The ARM build is failing to validate the `appdata.xml` file but the `amd64` is not:

```
  2/3 Validate appstream file                 FAIL     0.76 s (exit status 1)
  
  --- command ---
  /usr/bin/appstream-util validate-relax data/com.github.joseexposito.touche.appdata.xml
  --- stdout ---
  data/com.github.joseexposito.touche.appdata.xml: FAILED:
  • file-invalid          : <screenshot> failed to load [https://raw.githubusercontent.com/JoseExposito/touche/master/.github/images/elementary.png]
  • file-invalid          : <screenshot> failed to load [https://raw.githubusercontent.com/JoseExposito/touche/master/.github/images/elementary-dark.png]
  --- stderr ---
  Validation of files failed
```

**Comment by m-roberts** [comment]
The only thing that should be different is that it is using QEMU to emulate different architecture. I'm not sure why that would be happening! Perhaps we can look into this more together if you continue to experience issues.

**Comment by JoseExposito** [comment]
I temporary disabled the `appdata.xml` file validation, and it seems that is the only issue that's stopping the build to work: 
https://github.com/JoseExposito/touche/actions/runs/577360628

After a quick Google search I found [this project](https://github.com/lukechilds/dockerpi#which-machines-are-supported) and it seems like they also have the same issue:

> Note: Pi 2 and Pi 3 support is currently experimental. Networking doesn't work and QEMU hangs once the machines are powered down requiring you to docker kill the container. See #4 for details.

I don't know if this could be relevant:
https://stackoverflow.com/questions/61562014/qemu-kernel-for-raspberry-pi-3-with-networking-and-virtio-support/64420363#64420363
