### ISSUE TITLE
Cannot set a keyboard shortcut

### ISSUE THREAD

**Issue by linusrg1** [JoseExposito/touche#53]
### Describe the bug
When I try to set a keyboard shortcut the program does not accept my keyboard's input
A clear and concise description of what the bug is and how to reproduce it.
If you try and set 3 finger swipe gestures for apps that map to a keyboard shortcut it will not accept your keyboard input. 
### Expected behaviour
The tool successfully accepts you keyboard input and maps it to your gestures 

### Actual behaviour

It does not accept the input and instead stays it its waiting state it enters when waiting for input.

### Your environment

 * Touché version: unsure but probably the latest considering I got it from the aur.
 * Touchégg version:2.0.12.
 * Operating System:  Arch 
 * Desktop Environment:  KDE
 * Installation method: Via the aur

**Comment by JoseExposito** [comment]
Could you double check that are on X11 and not Wayland, please? Touchégg is an X11 only tool:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

If you are on X11, please run Touché from the command line and attach the output. Hopefully, it'll contain something useful.

**Comment by linusrg1** [comment]
Thank you was on wayland, just assumed that like most other distros arch would also use x11 by default but it didnt.

**Comment by JoseExposito** [comment]
Cool, no problem :)
