### ISSUE TITLE
Unable to assign FireFox shortcuts to swipe

### ISSUE THREAD

**Issue by rastacalavera** [JoseExposito/touche#56]
### Describe the bug
When I am trying to create a keyboard shortcut in Touche, when i click on the shortcut area, nothing happens and key inputs are not recognized.

### Expected behaviour

I thought it would operate like setting a global short cut where it shows the user input (example, I wanted "alt+L_arrow" as a three finger swipe right gesture in firefox)

### Actual behaviour

Nothing happens

### Logs

Flatpak output
(com.github.joseexposito.touche:2): Gjs-CRITICAL **: 14:52:40.578: JS ERROR: TypeError: surface.get_xid is not a function
grabKeyboard@webpack:///../src/main-view/content/shortcut-button.js?:74:25
_init/<@webpack:///../src/main-view/content/shortcut-button.js?:56:40
main@webpack:///../src/index.js?:58:22
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.joseexposito.touche:11:17

### Your environment

 * Touché version: 2.0.2
 * Touchégg version: v2.0.12.
 * Operating System: Fedora 35
 * Desktop Environment: Gnome 40
 * Installation method: Flatpak

**Comment by JoseExposito** [comment]
Are you using Wayland? Touchégg/Touché are X11 tools:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

**Comment by rastacalavera** [comment]
Oh geeze....completely missed that in the readme This is my first time trying out Fedora and I forgot the whole wayland thing. Closing the issue.

**Comment by JoseExposito** [comment]
No problem, enjoy your new Fedora install, it's a pretty cool distro!
