### ISSUE TITLE
The System theme is not respected

### ISSUE THREAD

**Issue by tio-trom** [JoseExposito/touche#59]
Using Arch + XFCE via Manjaro. Touche version 2.0.2-1.

This is how Touche looks on my system:

![2022-01-13_13-57](https://user-images.githubusercontent.com/38043315/149334433-db92ccae-eba3-4613-a69b-b97042a9fe8d.png)

The theme is not respected - I use a dark theme and Touche has a light theme. The window buttons are to the opposite side and they lack the maximize and minimize ones. This is a recent bug I think since it used to work well some 2 weeks ago.

Cheers!

**Comment by JoseExposito** [comment]
This is expected on Flatpak apps:
https://docs.flatpak.org/en/latest/desktop-integration.html#theming

If you Google "flatpak themes" you'll find different guides about how to use your own theme.

To be honest, I have never applied a theme to a Flatpak application and I don't know if it is going to work, so do it at your own risk.

**Comment by tio-trom** [comment]
I am not using the flatpak version tho. Not from what I can tell. Manjaro has a reo package and a flatpak package. I have the repo one.

**Comment by tio-trom** [comment]
I have installed the AUR version https://aur.archlinux.org/packages/touche and I see them same issue. Are you saying that the AUR is using the flatpak?

**Comment by JoseExposito** [comment]
> Are you saying that the AUR is using the flatpak?

No, I'm not saying that, the AUR version uses the native package, I assumed you were using Flatpak because it is a known "issue" of the platform.

> This is a recent bug I think since it used to work well some 2 weeks ago.

That's interesting, the AUR package was updated on 2021-11-28, so the application shouldn't have changed... Unless one of its dependencies has changed. Probably libadwaita.

Do you have the same problem with other GNOME apps?

**Comment by tio-trom** [comment]
No, all of the Gnome apps respect the theme. Gnome Calculator, Gnome Boxes, Gnome Photos, and so forth. Touche is the only "weird" one.

**Comment by tio-trom** [comment]
Just a question: does it mean that when the gnome apps will use libadwaita there is no way to respect the system theme, only toggle between light and dark?

**Comment by JoseExposito** [comment]
Most likely, yes, but we will see how things evolve. In case you are curious, this is a good video explaining the situation:
https://youtu.be/Pdx_MwcMtnM

**Comment by tio-trom** [comment]
Ah I see, This is sad. And very backwards for the end user at least. Thank you for the link!

**Comment by joe733** [comment]
![image](https://user-images.githubusercontent.com/38415384/234202095-4a97deaa-520a-47a2-a0c8-7a9e480db6b1.png)

The close button (:red_circle:) is in the opposite direction in `touche`. Is that a bug?

**Comment by jonathannerat** [comment]
Just run into this problem as well, a quick-fix is to force the gtk theme by, for example, modifying the default `.desktop` file shipped:

- Copy `/usr/share/applications/com.github.joseexposito.touche.desktop` to `~/.local/share/applications/`
- Change the line starting with `Exec=...` to: `Exec=env GTK_THEME=Adwaita-dark com.github.joseexposito.touche` or to any other theme you have installed
- Now you can start Touche from your launcher of choice, and it will the specified theme
