### ISSUE TITLE
It does not perform any gestures 

### ISSUE THREAD

**Issue by fignupafya** [JoseExposito/touche#60]
It does not perform any actions. I don't know the issue and how to fix this. I would appreciate the helps. (I do not know what to say to describe the problem so ask for something and i will give info about what you will ask for)

**Comment by JoseExposito** [comment]
If you don't mind, run in a terminal this command and attach its output:

```
$ touchegg --debug
```

If it exists with error "Another instance of Touchégg is already running", run `killall touchegg` (**no** sudo!!) and try again, please.

Make sure that you are on X11, Touchégg is a X11 only tool:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

**Comment by fignupafya** [comment]
> If you don't mind, run in a terminal this command and attach its output:
> 
> ```
> $ touchegg --debug
> ```
> 
> If it exists with error "Another instance of Touchégg is already running", run `killall touchegg` (**no** sudo!!) and try again, please.
> 
> Make sure that you are on X11, Touchégg is a X11 only tool: https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

Output after running `killall touchegg` :

`Touchégg v2.0.13.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/ahmet/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
^C
`
Note: Idk what is x11 actually

**Comment by JoseExposito** [comment]
What distro are you using? And how did you installed Touchegg?

It looks like you need to enable the service:
https://github.com/JoseExposito/touchegg#arch-linux-manjaro-and-derivatives

(The instructions are for Arch, but those 2 systemctl commands should solve your issue)

**Comment by fignupafya** [comment]
> What distro are you using? And how did you installed Touchegg?
> 
> It looks like you need to enable the service: https://github.com/JoseExposito/touchegg#arch-linux-manjaro-and-derivatives
> 
> (The instructions are for Arch, but those 2 systemctl commands should solve your issue)

After doing these now I can see the gestures on debug mode but it still does not perform any tasks. And i installed Touchegg first with the .deb , later i downloaded the Touché form flathub.

**Comment by fignupafya** [comment]
[touchegg-debug-result.txt](https://github.com/JoseExposito/touche/files/8119167/touchegg-debug-result.txt)
[touchegg.conf.txt](https://github.com/JoseExposito/touche/files/8119170/touchegg.conf.txt)
I just realized that pinching works and it is quite good. Swiping does not work unfortunately. By the way thanks a lot for your attention.

**Comment by JoseExposito** [comment]
OK, so, gestures are being detected, but they don't reach the 20% threshold required to execute their action. I imagine that in your recording you performed a long swipe (i.e., moved your fingers more than a few millimeters at this point:

```
Gesture begin detected    
        Gesture information:
                Fingers: 3
                Type: SWIPE
                Direction: UP
        Gesture performed on app: qterminal
        Action configured for this gesture
        Starting action
Gesture update detected (0.867541%)
Gesture update detected (1.18659%)
Gesture update detected (1.21559%)
Gesture update detected (1.24459%)
Gesture update detected (1.2736%)
Gesture update detected (1.33161%)
Gesture update detected (1.38961%)
Gesture end detected
```

This is probably because the size of your touchpad is unknown. Could you confirm it following this instructions?
https://github.com/JoseExposito/touchegg#daemon-configuration

Let me know if you need help following the instructions and I'll help you.
