### ISSUE TITLE
Can the software be Made Chinese? 软件可以汉化吗？

### ISSUE THREAD

**Issue by Brannua** [JoseExposito/touche#61]
Can the software be Made Chinese? 软件可以汉化吗？

**Comment by JoseExposito** [comment]
Unfortunately I don't speak Chinese, but with your help it can be translated. If you can send me this template translated, I'll add it to the project:

```
# Copyright 2020 - 2022 José Expósito <jose.exposito89@gmail.com>
# This file is distributed under the same license as the com.github.joseexposito.touche package.
# YOUR NAME <YOUR_EMAIL@ADDRESS>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: 1.0.0\n"
"Report-Msgid-Bugs-To: https://github.com/JoseExposito/touche/issues\n"
"POT-Creation-Date: 2022-02-19 16:31+0100\n"
"PO-Revision-Date: 2022-02-19 16:31+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "Add application"
msgstr ""

msgid "Add gestures for an application. Click on it's window"
msgstr ""

msgid "Arrow up"
msgstr ""

msgid "Arrow down"
msgstr ""

msgid "Arrow left"
msgstr ""

msgid "Arrow right"
msgstr ""

msgid "Close a window"
msgstr ""

msgid "Maximize a window"
msgstr ""

msgid "Restore a window"
msgstr ""

msgid "Minimize a window"
msgstr ""

msgid "Show desktop"
msgstr ""

msgid "Hide desktop"
msgstr ""

msgid "Tile window to the left half of the screen"
msgstr ""

msgid "Tile window to the right half of the screen"
msgstr ""

msgid "Without animation"
msgstr ""

msgid "Up"
msgstr ""

msgid "Down"
msgstr ""

msgid "Left"
msgstr ""

msgid "Right"
msgstr ""

msgid "In"
msgstr ""

msgid "Out"
msgstr ""

msgid "Unknown"
msgstr ""

msgid "Maximize or restore a window"
msgstr ""

msgid "Tile a window"
msgstr ""

msgid "Toggle fullscreen mode"
msgstr ""

msgid "Switch desktop"
msgstr ""

msgid "Keyboard shortcut"
msgstr ""

msgid "Execute a command"
msgstr ""

msgid "Mouse click"
msgstr ""

msgid "Used by GNOME"
msgstr ""

msgid "Unknown action"
msgstr ""

msgid "Global gestures"
msgstr ""

msgid "Add new application"
msgstr ""

msgid "Remove the selected application"
msgstr ""

msgid "Applications"
msgstr ""

#, javascript-format
msgid "Swipe with %d fingers"
msgstr ""

#, javascript-format
msgid "Tap with %d fingers"
msgstr ""

msgid "Only available on touchscreens"
msgstr ""

msgid ""
"Tap gestures are only available on touchscreens. Tapping on a touchpad is "
"not available"
msgstr ""

msgid "Click here to add shortcut"
msgstr ""

msgid "Shortcut:"
msgstr ""

msgid "Repeat command:"
msgstr ""

msgid "Execute on:"
msgstr ""

msgid "Gesture begin"
msgstr ""

msgid "Gesture end"
msgstr ""

msgid "Opposite keys:"
msgstr ""

msgid "Animation:"
msgstr ""

msgid "Mouse button:"
msgstr ""

msgid "Left click"
msgstr ""

msgid "Right click"
msgstr ""

msgid "Middle click"
msgstr ""

msgid "Command:"
msgstr ""

msgid "Opposite command:"
msgstr ""

msgid "Run this command when the gesture goes in the opposite direction"
msgstr ""

msgid "Direction:"
msgstr ""

msgid "Swipe"
msgstr ""

msgid "Pinch"
msgstr ""

msgid "Tap"
msgstr ""

#, javascript-format
msgid "Pinch with %d fingers"
msgstr ""

msgid "Touchégg is not installed"
msgstr ""

msgid "It looks like Touchégg is not installed, let's start by downloading it"
msgstr ""

msgid "Download Touchégg"
msgstr ""

msgid "I just installed it"
msgstr ""
```

**Comment by Brannua** [comment]
> Ok, I'll try it later.

**Comment by Brannua** [comment]
Does the software consider a black theme?Add a button to toggle light and dark modes.

**Comment by JoseExposito** [comment]
> Ok, I'll try it later

Cool, thanks :D

> Does the software consider a black theme?Add a button to toggle light and dark modes.

Not yet, but GNOME 42 (to be released in ~1 month) will include a system level preference, and I'll update the app to work with it.

**Comment by Brannua** [comment]
> > Ok, I'll try it later
> 
> Cool, thanks :D
> 
> > Does the software consider a black theme?Add a button to toggle light and dark modes.
> 
> Not yet, but GNOME 42 (to be released in ~1 month) will include a system level preference, and I'll update the app to work with it.

Thank you, look forward to KDE desktop environment in your software can also have dark effect.

**Comment by Brannua** [comment]
# This file is distributed under the same license as the com.github.joseexposito.touche package.
# YOUR NAME <YOUR_EMAIL@ADDRESS>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: 1.0.0\n"
"Report-Msgid-Bugs-To: https://github.com/JoseExposito/touche/issues\n"
"POT-Creation-Date: 2022-02-19 16:31+0100\n"
"PO-Revision-Date: 2022-02-19 16:31+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "添加应用程序"
msgstr ""

msgid "为应用程序添加手势. 请点击它的窗口"
msgstr ""

msgid "箭头向上"
msgstr ""

msgid "箭头向下"
msgstr ""

msgid "箭头向左"
msgstr ""

msgid "箭头向右"
msgstr ""

msgid "关闭窗口"
msgstr ""

msgid "将窗口最大化"
msgstr ""

msgid "将窗口还原"
msgstr ""

msgid "将窗口最小化"
msgstr ""

msgid "显示桌面"
msgstr ""

msgid "隐藏桌面"
msgstr ""

msgid "将窗口平铺到屏幕的左半边"
msgstr ""

msgid "将窗口平铺到屏幕的右半边"
msgstr ""

msgid "无动效"
msgstr ""

msgid "向上"
msgstr ""

msgid "向下"
msgstr ""

msgid "向左"
msgstr ""

msgid "向右"
msgstr ""

msgid "向内"
msgstr ""

msgid "向外"
msgstr ""

msgid "未知"
msgstr ""

msgid "最大化或还原窗口"
msgstr ""

msgid "将窗口平铺"
msgstr ""

msgid "切换全屏模式"
msgstr ""

msgid "切换桌面"
msgstr ""

msgid "键盘快捷键"
msgstr ""

msgid "执行一条命令"
msgstr ""

msgid "用鼠标点击"
msgstr ""

msgid "被 GNOME 使用"
msgstr ""

msgid "未知的动作"
msgstr ""

msgid "全局手势"
msgstr ""

msgid "添加新应用"
msgstr ""

msgid "删除选定的应用程序"
msgstr ""

msgid "应用程序"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指轻扫"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指轻敲"
msgstr ""

msgid "只能在触摸屏上使用"
msgstr ""

msgid "点击手势只能在触摸屏上使用。不支持轻按触摸板"
msgstr ""

msgid "点击这里添加快捷方式"
msgstr ""

msgid "快捷方式："
msgstr ""

msgid "重复命令："
msgstr ""

msgid "执行时机:"
msgstr ""

msgid "动作开始"
msgstr ""

msgid "动作结束"
msgstr ""

msgid "相反的键："
msgstr ""

msgid "动效："
msgstr ""

msgid "鼠标按键："
msgstr ""

msgid "左键单击"
msgstr ""

msgid "右键单击"
msgstr ""

msgid "中键单击"
msgstr ""

msgid "命令："
msgstr ""

msgid "相反的命令:"
msgstr ""

msgid "当手势指向相反的方向时运行此命令"
msgstr ""

msgid "方向："
msgstr ""

msgid "轻扫"
msgstr ""

msgid "捏合"
msgstr ""

msgid "轻敲"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指进行捏合"
msgstr ""

msgid "未安装 Touchégg"
msgstr ""

msgid "看起来您还没有安装 Touchégg, 请首先下载它"
msgstr ""

msgid "下载 Touchégg"
msgstr ""

msgid "我刚刚安装了它"
msgstr ""

**Comment by Brannua** [comment]
> Unfortunately I don't speak Chinese, but with your help it can be translated. If you can send me this template translated, I'll add it to the project:
> 
> ```
> # Copyright 2020 - 2022 José Expósito <jose.exposito89@gmail.com>
> # This file is distributed under the same license as the com.github.joseexposito.touche package.
> # YOUR NAME <YOUR_EMAIL@ADDRESS>, 2022.
> #
> msgid ""
> msgstr ""
> "Project-Id-Version: 1.0.0\n"
> "Report-Msgid-Bugs-To: https://github.com/JoseExposito/touche/issues\n"
> "POT-Creation-Date: 2022-02-19 16:31+0100\n"
> "PO-Revision-Date: 2022-02-19 16:31+0100\n"
> "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
> "Language-Team: LANGUAGE <LL@li.org>\n"
> "Language: zh\n"
> "MIME-Version: 1.0\n"
> "Content-Type: text/plain; charset=UTF-8\n"
> "Content-Transfer-Encoding: 8bit\n"
> 
> msgid "Add application"
> msgstr ""
> 
> msgid "Add gestures for an application. Click on it's window"
> msgstr ""
> 
> msgid "Arrow up"
> msgstr ""
> 
> msgid "Arrow down"
> msgstr ""
> 
> msgid "Arrow left"
> msgstr ""
> 
> msgid "Arrow right"
> msgstr ""
> 
> msgid "Close a window"
> msgstr ""
> 
> msgid "Maximize a window"
> msgstr ""
> 
> msgid "Restore a window"
> msgstr ""
> 
> msgid "Minimize a window"
> msgstr ""
> 
> msgid "Show desktop"
> msgstr ""
> 
> msgid "Hide desktop"
> msgstr ""
> 
> msgid "Tile window to the left half of the screen"
> msgstr ""
> 
> msgid "Tile window to the right half of the screen"
> msgstr ""
> 
> msgid "Without animation"
> msgstr ""
> 
> msgid "Up"
> msgstr ""
> 
> msgid "Down"
> msgstr ""
> 
> msgid "Left"
> msgstr ""
> 
> msgid "Right"
> msgstr ""
> 
> msgid "In"
> msgstr ""
> 
> msgid "Out"
> msgstr ""
> 
> msgid "Unknown"
> msgstr ""
> 
> msgid "Maximize or restore a window"
> msgstr ""
> 
> msgid "Tile a window"
> msgstr ""
> 
> msgid "Toggle fullscreen mode"
> msgstr ""
> 
> msgid "Switch desktop"
> msgstr ""
> 
> msgid "Keyboard shortcut"
> msgstr ""
> 
> msgid "Execute a command"
> msgstr ""
> 
> msgid "Mouse click"
> msgstr ""
> 
> msgid "Used by GNOME"
> msgstr ""
> 
> msgid "Unknown action"
> msgstr ""
> 
> msgid "Global gestures"
> msgstr ""
> 
> msgid "Add new application"
> msgstr ""
> 
> msgid "Remove the selected application"
> msgstr ""
> 
> msgid "Applications"
> msgstr ""
> 
> #, javascript-format
> msgid "Swipe with %d fingers"
> msgstr ""
> 
> #, javascript-format
> msgid "Tap with %d fingers"
> msgstr ""
> 
> msgid "Only available on touchscreens"
> msgstr ""
> 
> msgid ""
> "Tap gestures are only available on touchscreens. Tapping on a touchpad is "
> "not available"
> msgstr ""
> 
> msgid "Click here to add shortcut"
> msgstr ""
> 
> msgid "Shortcut:"
> msgstr ""
> 
> msgid "Repeat command:"
> msgstr ""
> 
> msgid "Execute on:"
> msgstr ""
> 
> msgid "Gesture begin"
> msgstr ""
> 
> msgid "Gesture end"
> msgstr ""
> 
> msgid "Opposite keys:"
> msgstr ""
> 
> msgid "Animation:"
> msgstr ""
> 
> msgid "Mouse button:"
> msgstr ""
> 
> msgid "Left click"
> msgstr ""
> 
> msgid "Right click"
> msgstr ""
> 
> msgid "Middle click"
> msgstr ""
> 
> msgid "Command:"
> msgstr ""
> 
> msgid "Opposite command:"
> msgstr ""
> 
> msgid "Run this command when the gesture goes in the opposite direction"
> msgstr ""
> 
> msgid "Direction:"
> msgstr ""
> 
> msgid "Swipe"
> msgstr ""
> 
> msgid "Pinch"
> msgstr ""
> 
> msgid "Tap"
> msgstr ""
> 
> #, javascript-format
> msgid "Pinch with %d fingers"
> msgstr ""
> 
> msgid "Touchégg is not installed"
> msgstr ""
> 
> msgid "It looks like Touchégg is not installed, let's start by downloading it"
> msgstr ""
> 
> msgid "Download Touchégg"
> msgstr ""
> 
> msgid "I just installed it"
> msgstr ""
> ```

```
# This file is distributed under the same license as the com.github.joseexposito.touche package.
# YOUR NAME <YOUR_EMAIL@ADDRESS>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: 1.0.0\n"
"Report-Msgid-Bugs-To: https://github.com/JoseExposito/touche/issues\n"
"POT-Creation-Date: 2022-02-19 16:31+0100\n"
"PO-Revision-Date: 2022-02-19 16:31+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "添加应用程序"
msgstr ""

msgid "为应用程序添加手势. 请点击它的窗口"
msgstr ""

msgid "箭头向上"
msgstr ""

msgid "箭头向下"
msgstr ""

msgid "箭头向左"
msgstr ""

msgid "箭头向右"
msgstr ""

msgid "关闭窗口"
msgstr ""

msgid "将窗口最大化"
msgstr ""

msgid "将窗口还原"
msgstr ""

msgid "将窗口最小化"
msgstr ""

msgid "显示桌面"
msgstr ""

msgid "隐藏桌面"
msgstr ""

msgid "将窗口平铺到屏幕的左半边"
msgstr ""

msgid "将窗口平铺到屏幕的右半边"
msgstr ""

msgid "无动效"
msgstr ""

msgid "向上"
msgstr ""

msgid "向下"
msgstr ""

msgid "向左"
msgstr ""

msgid "向右"
msgstr ""

msgid "向内"
msgstr ""

msgid "向外"
msgstr ""

msgid "未知"
msgstr ""

msgid "最大化或还原窗口"
msgstr ""

msgid "将窗口平铺"
msgstr ""

msgid "切换全屏模式"
msgstr ""

msgid "切换桌面"
msgstr ""

msgid "键盘快捷键"
msgstr ""

msgid "执行一条命令"
msgstr ""

msgid "用鼠标点击"
msgstr ""

msgid "被 GNOME 使用"
msgstr ""

msgid "未知的动作"
msgstr ""

msgid "全局手势"
msgstr ""

msgid "添加新应用"
msgstr ""

msgid "删除选定的应用程序"
msgstr ""

msgid "应用程序"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指轻扫"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指轻敲"
msgstr ""

msgid "只能在触摸屏上使用"
msgstr ""

msgid "点击手势只能在触摸屏上使用。不支持轻按触摸板"
msgstr ""

msgid "点击这里添加快捷方式"
msgstr ""

msgid "快捷方式："
msgstr ""

msgid "重复命令："
msgstr ""

msgid "执行时机:"
msgstr ""

msgid "动作开始"
msgstr ""

msgid "动作结束"
msgstr ""

msgid "相反的键："
msgstr ""

msgid "动效："
msgstr ""

msgid "鼠标按键："
msgstr ""

msgid "左键单击"
msgstr ""

msgid "右键单击"
msgstr ""

msgid "中键单击"
msgstr ""

msgid "命令："
msgstr ""

msgid "相反的命令:"
msgstr ""

msgid "当手势指向相反的方向时运行此命令"
msgstr ""

msgid "方向："
msgstr ""

msgid "轻扫"
msgstr ""

msgid "捏合"
msgstr ""

msgid "轻敲"
msgstr ""

#, javascript-format
msgid "使用 %d 个手指进行捏合"
msgstr ""

msgid "未安装 Touchégg"
msgstr ""

msgid "看起来您还没有安装 Touchégg, 请首先下载它"
msgstr ""

msgid "下载 Touchégg"
msgstr ""

msgid "我刚刚安装了它"
msgstr ""
```

**Comment by Brannua** [comment]
Do you need to translate the rest of the content?

**Comment by Brannua** [comment]
It's midnight now. I'll take a rest. Good night.

**Comment by JoseExposito** [comment]
Hi! I just added your translations:
https://github.com/JoseExposito/touche/blob/master/po/zh.po

Thank you very much!! If in the future you want to update them, you can create a pull request.

I'll try to generate a release this week so your translations are available for everyone.
Thanks again!

**Comment by Brannua** [comment]
> Hi! I just added your translations: https://github.com/JoseExposito/touche/blob/master/po/zh.po
> 
> Thank you very much!! If in the future you want to update them, you can create a pull request.
> 
> I'll try to generate a release this week so your translations are available for everyone. Thanks again!

You're welcome, your software is really great.
