### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by hackerkerala** [JoseExposito/touche#62]
### Describe the bug
When i try to maximise the app it is showing a black color and then maximising it any fix for this
A clear and concise description of what the bug is and how to reproduce it.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

### Logs

If required, include logs of the bug:

```
$ flatpak run com.github.joseexposito.touche
# or
$ com.github.joseexposito.touche
```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Touché version:
 * Touchégg version:
 * Operating System: Ubuntu, Fedora, Arch Linux...
 * Desktop Environment: Gnome, KDE, Xfce...
 * Installation method: Flatpak, Debian package...

**Comment by JoseExposito** [comment]
Could you share your environment details, please? Distro, desktop environment, etc.

Is the screen fully black? Or does it show an animation similar to [this one](https://github.com/JoseExposito/touchegg#maximize-or-restore-a-window-maximize_restore_window) but using black instead of blue?

**Comment by hackerkerala** [comment]
I think so its like that it only shows when i maximise or minimise it shows a balck screen with 1sec lag and then maximise the screen

**Comment by JoseExposito** [comment]
If the screen is fully black (i.e., not showing an animation) it is most likely because you are not using a composition manager.

It is difficult to tell without your system details and/or a recording of a bug, but that's probably the cause.

**Comment by hackerkerala** [comment]
Is there any way to fix it

**Comment by ALBINPRAVEEN** [comment]
Im using kde(kali pinux)and my spec is intel i3 7th gen 4gb ram

**Comment by JoseExposito** [comment]
@hackerkerala it depends on your desktop environment, graphics card driver (NVIDIA could be problematic), etc 

For example, on KDE, enable composition in settings:
https://fitzcarraldoblog.wordpress.com/2011/09/08/toggle-kwin-compositing-on-and-off-easily-from-your-desktop/#:~:text=One%20way%20to%20enable%2Fdisable,to%20use%20a%20keyboard%20shortcut.

@ALBINPRAVEEN wrong bug report?
