### ISSUE TITLE
Touche on Arch Linux not detecting Touchegg

### ISSUE THREAD

**Issue by Arkapravo-Ghosh** [JoseExposito/touche#66]
# Touche on Arch Linux not detecting Touchegg
Recently I've installed touche in Arch Linux from AUR and I had touchegg-git installed from AUR. touchegg-git works properly although touche cannot detect touchegg-git. I've tried replacing touchegg-git with touchegg and also tried the flatpak build of touche. None of them detected touchegg in system. I've checked that my PATH is correct too. Please help.

![image](https://user-images.githubusercontent.com/65386474/158047328-317f7542-286d-47cc-933e-5349728e0edc.png)

![image](https://user-images.githubusercontent.com/65386474/158047386-1ec849eb-d37a-4326-9b8e-42e05aa4d85a.png)

**Comment by JoseExposito** [comment]
This error happens when the default configuration file is not present, by default placed at `/usr/share/touchegg/touchegg.conf`.

Could you check if the file exists, please?

**Comment by Arkapravo-Ghosh** [comment]
Thanks, it worked after manually creating the file.

**Comment by timgreen** [comment]
I was install to `/usr/local/`, and just making a copy of the default config doesn't work for me.

I have to install again with `-DCMAKE_INSTALL_PREFIX=/usr`, then everything works fine after.
