### ISSUE TITLE
Install Touché without Gnome 42

### ISSUE THREAD

**Issue by fabian-st** [JoseExposito/touche#76]
When I install Touché using Flatpak, it lists the following dependencies:

       ID                                      Branch   Op  Remote   Download
       ...
       5.     org.gnome.Platform.Locale               42       i   flathub  < 336,0 MB (partial)
       ...
       7.     org.gnome.Platform                      42       i   flathub  < 276,2 MB
       ...

Does that mean it will update Gnome to version 42?
If so, what can I do to prevent this and stay on 3.36.8?

BW

**Comment by JoseExposito** [comment]
Hi,

There is nothing to worry about. That dependency is not GNOME it self, it is a "runtime" used by Flatpak. A runtime is a set of common libraries used by GNOME apps. They are placed in a common package so they can be reused and save some space on your hard drive.

It won't replace your GNOME version, you can safely install and uninstall Flatpak apps without affecting your system at all.
