### ISSUE TITLE
Touche fails to launch due to TypeError.

### ISSUE THREAD

**Issue by hridampalwe** [JoseExposito/touche#77]
### Describe the bug

A clear and concise description of what the bug is and how to reproduce it.

Touche fails to launch with the error : 
` (com.github.joseexposito.touche:24215): Gjs-CRITICAL **: 14:55:49.048: JS ERROR: TypeError: can't redefine non-configurable property "toString" 
`

### Expected behaviour
Launch Touche normally.

### Actual behaviour

Touche fails to launch with above error.

### Logs

```
(com.github.joseexposito.touche:24215): Gjs-CRITICAL **: 14:55:49.048: JS ERROR: TypeError: can't redefine non-configurable property "toString"
module.exports<@webpack:///../node_modules/core-js/internals/create-non-enumerable-property.js?:8:31
module.exports@webpack:///../node_modules/core-js/internals/redefine.js?:52:62
@webpack:///../node_modules/core-js/internals/redefine.js?:53:3
../node_modules/core-js/internals/redefine.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1108:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1559:41
@webpack:///../node_modules/core-js/internals/export.js?:7:35
../node_modules/core-js/internals/export.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:644:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1559:41
@webpack:///../node_modules/core-js/modules/es.regexp.exec.js?:3:28
../node_modules/core-js/modules/es.regexp.exec.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1423:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1559:41
@webpack:///../src/index.js?:2:110
../src/index.js@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:140:1
__webpack_require__@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1559:41
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1623:56
@resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js:1625:12
@/usr/bin/touche:11:1

```

### Your environment

 * Touché version: 2.0.6-1
 * Touchégg version: 2.0.14-2
 * Operating System: Endeavour OS 
 * Desktop Environment: KDE Plasma
 * Installation method: AUR Package

**Comment by bop34** [comment]
I am getting the same error. I just installed both Touchégg and Touché from the AUR. Running Arch.

**Comment by JoseExposito** [comment]
It looks like something changed under the hood in GJS (the JavaScript engine that is used by the app).

I'd suggest to use the Flatpak version while I find some time to fix the issue and release a new version:
https://flathub.org/apps/details/com.github.joseexposito.touche

**Comment by yochananmarqos** [comment]
Turns out Arch forgot to rebuild `gjs` against `js91`. GNOME Weather was also broken due to this.

`gjs` 2:1.72.0-2 fixes the issue. @JoseExposito The issue can be closed.

**Comment by JoseExposito** [comment]
Thanks for the quick feedback @yochananmarqos , closing it :+1:
