### ISSUE TITLE
Unable to build on EndeavourOS 

### ISSUE THREAD

**Issue by appleparan** [JoseExposito/touche#79]
### Describe the bug
When building 2.0.6 in arch based distro, `appstream-util` check failed.
* How to reproduce
```
$ yay -S touche
```
or 
```
$ git clone https://aur.archlinux.org/touche.git
$ cd touche
$ makepkg -si 
```

### Expected behaviour
Build without error

### Actual behaviour
```
==================================== 3/3 =====================================
test:         Validate appstream file
start time:   15:07:06
duration:     0.10s
result:       killed by signal 11 SIGSEGV
command:      MALLOC_PERTURB_=119 /usr/bin/appstream-util validate-relax data/com.github.joseexposito.touche.appdata.xml
----------------------------------- stdout -----------------------------------
data/com.github.joseexposito.touche.appdata.xml: 
----------------------------------- stderr -----------------------------------

(appstream-util:17440): GLib-GIO-CRITICAL **: 00:07:06.932: g_proxy_resolver_lookup: assertion 'G_IS_PROXY_RESOLVER (resolver)' failed
==============================================================================


Summary of Failures:

3/3 Validate appstream file FAIL            0.10s   killed by signal 11 SIGSEGV

Ok:                 2   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

```

### Your environment

 * Touché version: [2.0.6-1](https://aur.archlinux.org/packages/touche)
 * Touchégg version: [2.0.14-2 (aur/touchegg)](https://aur.archlinux.org/packages/touchegg)
 * Operating System: EndeavourOS(Arch Linux) Artemis 22_6
 * Desktop Environment: KDE
 * Installation method: yay
 * Are you using Wayland? If the anwser is yes, please have in mind that [Touchégg is a X11 only tool](https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland) **No**

**Comment by JoseExposito** [comment]
Hi!

[g_proxy_resolver_lookup](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gio/GProxyResolver.html#g-proxy-resolver-lookup) docs read:

"Looks into the system proxy configuration to determine what proxy, if any, to use to connect to uri"

I imagine it is doing some kind of validation of the URLs present in https://github.com/JoseExposito/touche/blob/master/data/app.appdata.xml.in.in

Could you check that your proxy configuration is correct and that you can reach the URLs present in that file, please? Also, make sure you have internet connection while building, i.e., if you are building inside a container or similar, make sure it can reach the internet.

You'd probably have more luck contacting one of your distro maintainers, I have never user EndeavourOS.

**Comment by appleparan** [comment]
After digging the issue, I found that it is [a bug of appstream-utils](https://github.com/hughsie/appstream-glib/issues/449) and is fixed. Close the issue because it doesn't belong to touche issue.
