### ISSUE TITLE
Warning when multiple GTK versions are installed

### ISSUE THREAD

**Issue by JoseExposito** [JoseExposito/touche#8]
### Describe the bug

When multiple versions of GTK are installed, Touché is throwing a warning:

```
Gjs-Message: 13:07:46.951: JS WARNING: [resource:///com/github/joseexposito/touche/js/com.github.joseexposito.touche.js line 305 > eval 25]: Requiring Gtk but it has 2 versions available; use imports.gi.versions to pick one
```

### Expected behaviour

It should target GTK 3

### Additional notes:

Reported by @yochananmarqos here https://github.com/JoseExposito/touche/issues/4#issuecomment-778437073

**Comment by emielbeinema** [comment]
With Gtk4 installed, this problem prevents me from starting the program. I've opened a PR to fix the warning/error. Could you take a look?

**Comment by yochananmarqos** [comment]
Works for me. I've applied the patch to the AUR package.

**Comment by JoseExposito** [comment]
Solved, thanks a lot @emielbeinema :rocket:

**Comment by emielbeinema** [comment]
Thank you for your quick action and great work!
