### ISSUE TITLE
Sorry, I want to uninstall, but i am dont know how to do

### ISSUE THREAD

**Issue by xiaobucvg** [JoseExposito/touche#80]
dear you:
    I am using ubuntu22.4.
    I download the release-2.0.6 and decompress it.
    I run command `npm run install` and `npm run build` then the software is installed.
    now, i want to uninstall it, but i dont know how to do...

**Comment by JoseExposito** [comment]
Hi!

You can use ninja:

```
$ ninja -C build uninstall
```

Best wishes,
Jose
