### ISSUE TITLE
App size is too big

### ISSUE THREAD

**Issue by JosuGZ** [JoseExposito/touche#84]
Am I reading this right? 3GB? What is in here? Will I save space building it myself?

![image](https://user-images.githubusercontent.com/25986871/206925763-667b7d3e-7000-4e45-934a-c059b035f58c.png)

**Comment by JoseExposito** [comment]
Hi Jozu,

Flatpak application use "runtimes" to share sets of common libraries. For example, Touché uses the GNOME runtime to have access to all the GNOME functionality.

Once that runtime is downloaded, it is shared by every Flatpak application installed in your system. So the real disck usage is way smaller than advertised in your screenshot.

Here is an article explaining it a bit better:
https://blogs.gnome.org/wjjt/2021/11/24/on-flatpak-disk-usage-and-deduplication/

I wouldn't worry too much about disck usage, most of the stuff is shared across Flatpak applications.

If you really can't afford to use those megabytes of your hard drive, you can build and install the app yourself, but I'd not recommend it, as I didn't test the app with other versions of its dependencies and I might or might not work.

Closing the issue for the moment, feel free to reopen it or comment if you have any further questions.

**Comment by JosuGZ** [comment]
Thanks for the explanation. I was able to configure it with the XML file though. I can finally switch tabs with the touchpad :)
