### ISSUE TITLE
Cycle through workspaces

### ISSUE THREAD

**Issue by Biloot** [JoseExposito/touche#86]
First, I'd like to say that I love this software, it works perfectly and is very useful.
But could it be possible to add a setting, so we can cycle through workspaces (the last workspace could be placed as the one before the first workspace)? Thanks!

**Comment by JoseExposito** [comment]
The option `cyclic` is available for manual configuration:
https://github.com/JoseExposito/touchegg#switch-desktopsworkspaces-change_desktop

You can add it to your config file.

It is not available in the UI though, that's a missing feature. Pull requests are very welcome :)

**Comment by Biloot** [comment]
Thanks!
