### ISSUE TITLE
Fails to build aur package

### ISSUE THREAD

**Issue by KarkanAlzwayed** [JoseExposito/touche#93]
### Describe the bug

Running endeavourOS and trying to install touche from the aur and it fails to build with this message 
```
KeyError: 'c'

subprojects/libtouche/meson.build:37:6: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
==> ERROR: A failure occurred in build().
    Aborting...
```
I can post the whole terminal output if needed. It is long and I chose to pick the error that it aborted on
### Expected behaviour
The app to install
Tell us what should happen.
The app should install without failing 
### Actual behaviour
Aur package fails to install
Tell us what happens instead.

### Logs

If required, include logs of the bug:

```
$ flatpak run com.github.joseexposito.touche
# or
$ com.github.joseexposito.touche
```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.
The touchegg folder doesn't exist in the path above, even though I did install and enable touchegg
### Your environment

 * Touché version: 2.0.9-1
 * Touchégg version: 2.0.17-1
 * Operating System: Endeavour OS
 * Desktop Environment: KDE
 * Installation method: AUR Package through terminal, bauh and octopi - all failed with the same error
 * Are you using Wayland? No

**Comment by JoseExposito** [comment]
Thanks for your bug report. I'm going to close this one so we can keep the conversation in https://github.com/JoseExposito/touche/issues/92.

Check my comment for a workaround.
