### ISSUE TITLE
Swipe up gesture does not maximize window nor restore a minimized window.

### ISSUE THREAD

**Issue by shifu-brighton** [JoseExposito/touche#96]
### Describe the bug

When I set the gesture to maximize/restore a minimized window, it doesn't work as expected. It actually simply does nothing at all. I have tried two fingers, three fingers and four finger gestures just incase its a bug for one gesture and not for the others, however it is a present bug in all of them.

I have no logs, I haven't delved that deep into the source code.

```
Used: $ flatpak run com.github.joseexposito.touche
```

### Your environment

 * Touché version: latest version as of January 2024
 * Touchégg version:v2.0.17
 * Operating System: Ubuntu
 * Desktop Environment:KDE
 * Installation method: Flatpak
 * Are you using Wayland? yes

**Comment by JoseExposito** [comment]
> Are you using Wayland? yes

Touchégg is a X11 only tool:
https://github.com/JoseExposito/touchegg?tab=readme-ov-file#does-touch%C3%A9gg-work-on-wayland
